/**
 * Simple PDF generation without complex features
 */
import jsPDF from 'jspdf';

export const generateSimplePDF = (messages, options = {}) => {
  try {
    console.log('Generating simple PDF...');
    
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = margin;
    
    // Add title
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('GrammarMate Q&A Session', margin, yPosition);
    yPosition += 20;
    
    // Add timestamp
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on: ${new Date().toLocaleString()}`, margin, yPosition);
    yPosition += 15;
    
    // Add separator line
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 15;
    
    // Process messages
    messages.forEach((msg, index) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 50) {
        pdf.addPage();
        yPosition = margin;
      }
      
      const role = msg.role === 'user' ? 'User' : 'AI Assistant';
      const content = msg.content;
      
      // Add role header
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${role}:`, margin, yPosition);
      yPosition += 8;
      
      // Add content
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      
      // Split long text into multiple lines
      const lines = pdf.splitTextToSize(content, pageWidth - (margin * 2));
      lines.forEach(line => {
        if (yPosition > pageHeight - 20) {
          pdf.addPage();
          yPosition = margin;
        }
        pdf.text(line, margin, yPosition);
        yPosition += 6;
      });
      
      // Add translation if exists
      if (msg.translated) {
        yPosition += 3;
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'italic');
        pdf.setTextColor(100, 100, 100);
        pdf.text(`Translation: ${msg.translated}`, margin, yPosition);
        yPosition += 6;
      }
      
      yPosition += 8; // Space between messages
    });
    
    // Add simple watermark to all pages
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      
      // Add watermark
      pdf.setFontSize(20);
      pdf.setTextColor(200, 200, 200);
      pdf.text('GrammarMate', pageWidth / 2, pageHeight / 2, {angle: -45});
      
      // Add footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by GrammarMate', margin, pageHeight - 10);
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10);
    }
    
    return pdf;
  } catch (error) {
    console.error('Simple PDF generation error:', error);
    throw error;
  }
};

export const downloadSimplePDF = (messages, options = {}) => {
  try {
    const pdf = generateSimplePDF(messages, options);
    
    // Generate filename
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = options.filename || `GrammarMate_QA_${timestamp}.pdf`;
    
    // Save the PDF
    pdf.save(filename);
    
    return {
      success: true,
      filename: filename,
      message: 'PDF exported successfully'
    };
  } catch (error) {
    console.error('Simple PDF download error:', error);
    return {
      success: false,
      error: error.message,
      message: 'Failed to generate PDF'
    };
  }
};
